import React from "react";
import Head from "next/head";
import Image from "next/image";

function Home() {
  return (
    <div className=" tracking-widest  bg-contain md:bg-cover bg-center home_bg">
    <div className="h-screen bg-slate-800 bg-opacity-80" >
    <Head>
      <title>PWA</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="flex justify-center w-full items-center content-center h-screen">
      <div className="block w-full bg-transparent  text-red-500  bg-opacity-25 px-2 py-2 shadow-md rounded-sm max-w-screen-xl">
         <div>
           <Image alt='' src='/images/home/2d-ori.png' width={30} height={30}  />
         </div>
        <div className="grid grid-flow-row grid-cols-12 gap-8">
          <div className="px-2 py-2 text-yellow-400 hover:shadow-lg rounded-sm bg-indigo-900 bg-opacity-40 col-span-12 md:col-span-4">
            <h6 className="text-sm font-thin text-white mb-2">
              Thailand working days
            </h6>
            <div className="flex w-full justify-between items-center content-center">
              <span className="text-xs font-thin">9:30AM-12:01PM</span>
              <span className="text-xs font-thin">2:00PM-4:30PM</span>
            </div>
          </div>
          <div className="px-2 py-2 text-yellow-400 hover:shadow-lg rounded-sm bg-indigo-900 bg-opacity-40 col-span-12 md:col-span-4">
            <div className="flex w-full justify-between items-center content-center">
            <h6 className="text-sm font-thin text-white w-full mb-2">
              SET market
            </h6>
            <h6 className="text-sm font-thin text-white w-full mb-2">
              To open(I)
            </h6>
            </div>
            <div className="flex w-full justify-between items-center content-center">
              <span className="text-xs text-red-500 font-thin w-full">Closed</span>
              <div className="text-xs font-thin w-full flex space-x-2">
                  <span className="px-2 py-1 rounded-md flex justify-center items-center content-center border"> {new Date().getHours()} </span> <span className="flex justify-center items-center content-center px-2 py-1">:</span>
                  <span className="px-2 py-1 rounded-md flex justify-center items-center content-center border"> {new Date().getMinutes()} </span> <span className="flex justify-center items-center content-center px-2 py-1">:</span>
                  <span className="px-2 py-1 rounded-md flex justify-center items-center content-center border"> {new Date().getUTCSeconds()} </span>
                  <span className="px-2 py-1 rounded-md flex justify-center items-center content-center"> AM </span>
              </div>
            </div>
          </div>
          <div className="px-2 py-2 text-yellow-400 hover:shadow-lg rounded-sm bg-indigo-900 bg-opacity-40 col-span-12 md:col-span-4">
            <div className="flex w-full justify-between items-center content-center">
            <h6 className="text-sm font-thin text-white w-full mb-2">
             SET
            </h6>
            <h6 className="text-sm font-thin text-white w-full mb-2">
             VALUE
            </h6>
            <h6 className="text-sm font-thin text-white w-full mb-2">
             2D Real Time
            </h6>
            </div>
            <div className="flex w-full justify-between items-center content-center">
            <p className="text-xs font-thin text-yellow-400 w-full mb-2">
            1677.24
            </p>
            <p className="text-xs font-thin text-yellow-400 w-full mb-2">
            76267.45
            </p>
            <p className="text-xs font-bold text-green-600 w-full mb-2">
            47
            </p>
            </div>
          </div>
        </div>
        <div className='mt-4'>
           <Image alt='' src='/images/home/2d.png' width={30} height={30}  />
         </div>
        <div className="grid grid-flow-row grid-cols-12 gap-8">
          <div className="px-2 py-2 text-yellow-400 hover:shadow-lg rounded-sm bg-indigo-900 bg-opacity-40 col-span-12 md:col-span-4">
            <h6 className="text-sm font-thin text-white mb-2">
              Thailand working days
            </h6>
            <div className="flex w-full justify-between items-center content-center">
              <span className="text-xs font-thin">9:30AM-12:01PM</span>
              <span className="text-xs font-thin">2:00PM-4:30PM</span>
            </div>
          </div>
          <div className="px-2 py-2 text-yellow-400 hover:shadow-lg rounded-sm bg-indigo-900 bg-opacity-40 col-span-12 md:col-span-4">
            <div className="flex w-full justify-between items-center content-center">
            <h6 className="text-sm font-thin text-white w-full mb-2">
              SET market
            </h6>
            <h6 className="text-sm font-thin text-white w-full mb-2">
              To open(I)
            </h6>
            </div>
            <div className="flex w-full justify-between items-center content-center">
              <span className="text-xs text-red-500 font-thin w-full">Closed</span>
              <div className="text-xs font-thin w-full flex space-x-2">
                  <span className="px-2 py-1 rounded-md flex justify-center items-center content-center border"> {new Date().getHours()} </span> <span className="flex justify-center items-center content-center px-2 py-1">:</span>
                  <span className="px-2 py-1 rounded-md flex justify-center items-center content-center border"> {new Date().getMinutes()} </span> <span className="flex justify-center items-center content-center px-2 py-1">:</span>
                  <span className="px-2 py-1 rounded-md flex justify-center items-center content-center border"> {new Date().getUTCSeconds()} </span>
                  <span className="px-2 py-1 rounded-md flex justify-center items-center content-center"> AM </span>
              </div>
            </div>
          </div>
          <div className="px-2 py-2 text-yellow-400 hover:shadow-lg rounded-sm bg-indigo-900 bg-opacity-40 col-span-12 md:col-span-4">
            <div className="flex w-full justify-between items-center content-center">
            <h6 className="text-sm font-thin text-white w-full mb-2">
             SET
            </h6>
            <h6 className="text-sm font-thin text-white w-full mb-2">
             VALUE
            </h6>
            <h6 className="text-sm font-thin text-white w-full mb-2">
             2D Real Time
            </h6>
            </div>
            <div className="flex w-full justify-between items-center content-center">
            <p className="text-xs font-thin text-yellow-400 w-full mb-2">
            1677.24
            </p>
            <p className="text-xs font-thin text-yellow-400 w-full mb-2">
            76267.45
            </p>
            <p className="text-xs font-bold text-green-600 w-full mb-2">
            47
            </p>
            </div>
          </div>
        </div>
        <div className="mt-6 flex justify-center w-full items-center content-center">
         
        </div>
      </div>
    </div>
    </div>
  </div>
  );
}

export default Home;
